environments:
    - Staging
    - Production

appicon:
    original: TestNatrium/resource/icon.jpg
    appiconset: TestNatrium/Assets.xcassets/AppIcon.appiconset/
    idioms:
        - iphone
    ribbon:
        Production:
            Debug: "PRODUCTION"
            Release: ""
        Staging:
            Debug: "STAGING"
            Release: ""
